algoritmo "semnome"
// Função : Média do Aluno
// Autor :  Antonio Lima
// Data : 26/11/2018
// Seção de Declarações 
var

n1,n2,media:real

inicio
escreva("Digite a primeira nota do aluno = ")
leia(n1)

escreva("Digite a segunda nota do aluno = ")
leia(n2)
media:=(n1+n2)/2

se(media>=6)entao
escreva("O aluno está aprovado")
senao
escreva("O aluno está reprovado")
fimse

fimalgoritmo
