algoritmo "Audiencia canais"
// Função : Listar canais e número de telespectadores
// Autor : Antonio Lima
// Data : 30/11/2018
// Seção de Declarações 
var
canal,telespectadores,pessoas,c4,c5,c7,c12:caractere


inicio
para pessoas de 1 ate 10 faca
escreva("Digite o número do canal: ")
leia(canal)
escreva("Digite o número de telespectadores locais: ")
leia(telespectadores)
se(canal=c4) entao
tc4:=telespectadores
se(canal
fimalgoritmo
