algoritmo "primeiro algoritmo"
// Função : Digitar um valor na faixa
// Autor :  Antonio Lima
// Data : 23/11/2018
// Seção de Declarações
var
n:inteiro

inicio
escreva("Digite um número = ")
leia(n)
se(n <=9) entao
escreva("O valor está na faixa permitida")
se(n>9) entao
escreva("O valor está fora da faixa permitida")
se(n <1) entao
escreva("O valor está fora da faixa permitida")

fimse

fimalgoritmo















