algoritmo "semnome"
// Função : Criar uma tabuada de multiplicar por um número escolhido pelo usuário
//que fará o cálculo contado de 0 a 10.
//Use a estrutura PARA.
// Autor :
// Data : 14/12/2018
// Seção de Declarações 
var
num,m,r:inteiro
inicio
escreva("Digite o número a ser multiplicado: ")
leia(num)
escreval("")
para m de 0 ate 10 faca
r:=num*m
escreval(num, "x" ,m, " = " ,r)
fimpara

fimalgoritmo
